// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLYtac3-ZQ1EcDye67TYxqRGfj-PCZPw',
    appId: '1:558846643955:android:bb10fe9b6d133217527186',
    messagingSenderId: '558846643955',
    projectId: 'appapa-a17ac',
    storageBucket: 'appapa-a17ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKm1IoRJhQqLTQu7duEaEo8Un05Idlpe4',
    appId: '1:558846643955:ios:41225a1307835f59527186',
    messagingSenderId: '558846643955',
    projectId: 'appapa-a17ac',
    storageBucket: 'appapa-a17ac.firebasestorage.app',
    iosBundleId: 'com.alexp.examen1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD02GDuPt7z9UoKUxKO9eclxyYD5mF5OqQ',
    appId: '1:558846643955:web:a1789b585aaafb87527186',
    messagingSenderId: '558846643955',
    projectId: 'appapa-a17ac',
    authDomain: 'appapa-a17ac.firebaseapp.com',
    storageBucket: 'appapa-a17ac.firebasestorage.app',
  );
}
